[package]
name = "sandbox"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "For developping and integration testing"
publish = false

[[bin]]
name = "sandbox"
path = "main.rs"

[dependencies]

[dev-dependencies]

[features]
default = []
