[package]
name = "ribble-net"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Networking primitives for the Ribble game engine"
publish = false

[lib]
name = "ribble_net"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]

[features]
default = []
