[package]
name = "ribble-assets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Asset loading and management for the Ribble game engine"
publish = false

[lib]
name = "ribble_assets"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]

[features]
default = []

