[package]
name = "ribble-editor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "In-engine editor overlay for the Ribble game engine"
publish = false

[lib]
name = "ribble_editor"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]

[features]
default = []
